### ISSUE TITLE
go: GOPATH entry is relative; must be absolute path: "".

### ISSUE THREAD

**Issue by p1vynodejs** [webchain-network/webchain-pool#1]
go: GOPATH entry is relative; must be absolute path: "".

how to fix this?

**Comment by lukaszmatczak** [comment]
You have to configure your environment. Please read guide on golang site: https://golang.org/doc/code.html#GOPATH

**Comment by p1vynodejs** [comment]
i have set the path, now i got this error:

github.com/webchain-network/webchaind/logger/glog
# github.com/webchain-network/webchaind/logger/glog
../webchaind/logger/glog/glog.go:1271: undefined: sort.Slice
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lukaszmatczak** [comment]
"sort" is standard go package. Looks like something is wrong with your golang installation or paths.

**Comment by lukaszmatczak** [comment]
Minimum go version is 1.8. I've updated README.md.
