### ISSUE TITLE
Update the pool protocol documentation?

### ISSUE THREAD

**Issue by Salketer** [webchain-network/webchain-pool#14]
I am trying to create a pool client, mostly for learning purposes and I am struggling with the pool communication.

The doc describes the stratum protocol used and says we should login like this:

```
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_submitLogin",
  "params": ["0xb85150eb365e7df0941f0cf08235f987ba91506a"]
}
```
But sending such a request returns this:
```
{"id":1,"jsonrpc":"2.0","result":null,"error":{"code":-3,"message":"Method not found"}}
```

Trying other stuff like:
```
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "login",
  "params": ["0xb85150eb365e7df0941f0cf08235f987ba91506a"]
}
```
Closes the socket right away but using this:

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "login",
  "params": {
  "login":"0xb85150eb365e7df0941f0cf08235f987ba91506a"
}

looks like it is working, as a job is received... But the doc says we should simply receive result:true?

Is there an up-to-date documentation available?

**Comment by lukaszmatczak** [comment]
According to Discord conversation, current documentation of stratum protocol used by pool can be found here: https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM.md
