### ISSUE TITLE
duplicate share problem

### ISSUE THREAD

**Issue by 2331832** [webchain-network/webchain-pool#2]
Try to lunch a pool at ubuntu 16.04 LTS, but when i test it most of my miners got "duplicate share" then connection reset.

Is there a way to work out this problem?

**Comment by lukaszmatczak** [comment]
Could you provide more details? For example pool logs.

**Comment by el-druida** [comment]
C'mon do something, only two pools have problems with duplicate share, invalid share etc etc. Your poll "pool.webchain.network" and "webcn.loudmining.com", others pools no have problems... 
![imagen](https://user-images.githubusercontent.com/15017402/47743924-e9105b80-dc5e-11e8-86d2-06601067ab54.png)
